name: AutoClearLagg
description: Recoded & improved auto clear lagg plugin 

main: Teunboeke\autoclearlagg\AutoClearLagg
version: 3.1.0
api: 3.0.0

author: Teunboeke 
website: https://github.com/Teunboeke/AutoClearLagg
